# Generated by Django 4.1 on 2022-08-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desc',
            new_name='description',
        ),
    ]
